# when running k8s cluster locally use : service types as NodePort with container port 31000 and image port 8000
apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 31000
    protocol: TCP
  selector:
    app: web
    
