# when running this service on CloudProvider use : service types as LoadBalancer with container port as 31000 and image port 8000
apiVersion: v1
kind: Service
metadata:
  name: web-lbsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80           > internet facing port when using service type as LoadBalancer
    targetPort: 8000   > container port which you have exposed in you Dockerfile
    protocol: TCP
  selector:
    run: web
    
