/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-03 06:35:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>OASS.com</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"free templates, website templates, CSS, HTML\" />\r\n");
      out.write("<meta name=\"description\" content=\"free website template provided by templatemo.com\" />\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"css/jquery.ennui.contentslider.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen,projection\" />\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("function clearText(field)\r\n");
      out.write("{\r\n");
      out.write("    if (field.defaultValue == field.value) field.value = '';\r\n");
      out.write("    else if (field.value == '') field.value = field.defaultValue;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<h1>About Us...</h1>\r\n");
      out.write("        \t<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n");
      out.write("        \t  <tbody>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"81%\"><p>\r\n");
      out.write("        \t        <h4 class=\"punit\">We are the guys of Sagar Institute of Research, Technology and Science, 6th semester students, graduating in the field of IT under this heavy name.</h4>\r\n");
      out.write("        \t        <span class=\"punit\">\r\n");
      out.write("        \t        </p>\r\n");
      out.write("       \t            \r\n");
      out.write("   \t                </span>\r\n");
      out.write("       \t          <p><h4 class=\"punit\">This site is constructed only for the purpose of our academic project and we have no plans for buying a web space and hosting this site over World Wide Web (WWW)</h4></p></td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\" align=\"right\">&nbsp;</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\" class=\"punit\">  <strong>CREDITS-<em> (in alphabetical order) </em></strong></td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">- <span class=\"punit\">Ankit Sharma</span></td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">- Punit Porwal</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">- Shashank Pawar</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">- Vivek Singhal</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">&nbsp;</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">&nbsp;</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">&nbsp;</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("        \t    <tr valign=\"bottom\">\r\n");
      out.write("        \t      <td width=\"61%\">&nbsp;</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t    </tbody>\r\n");
      out.write("      \t  </table>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t<div id=\"templatemo_footer\">\r\n");
      out.write("<a href=\"student1.jsp\">Home</a> | <a href=\"oass.jsp\">OASS</a> | <a href=\"about.jsp\">About</a> | <a href=\"terms.jsp\">Terms</a> | <a href=\"about.jsp\">Contact Us</a><br />\r\n");
      out.write("        Copyright &copy; 2010-2011 <a href=\"oass.jsp\">OASS</a>- Designed by ADMINS<a href=\"http://www.templatemo.com\" target=\"_blank\"></a></div>       \r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
