/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-03 06:35:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import online.*;

public final class oass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("online");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


response.setHeader("Cache-Control","no-cache");
response.setHeader("Pragma","no-cache");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>OASS(online assignment submision system.com</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"Free website, free template, website template, css layout, dark gray color\" />\r\n");
      out.write("<meta name=\"description\" content=\"Free Website, Free CSS Template provided by templatemo.com\" />\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("#templatemo_container #templatemo_leftcolumn #templatemo_sitetitle p {\r\n");
      out.write("\tfont-family: MS Serif, New York, serif;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("function validation()\r\n");
      out.write("{\r\n");
      out.write("if(!validString(document.thisform.EnrollNo,4,\"Invalid Enrollment Number\"))\r\n");
      out.write("return false;\r\n");
      out.write("if(!validNum(document.thisform.Password,6,\"Invalid Password\"))\r\n");
      out.write("return false;\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"templatemo_container\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"templatemo_leftcolumn\">\r\n");
      out.write("\t<div id=\"templatemo_sitetitle\">\r\n");
      out.write("\t\t<div class=\"title\"> OASS<span></span></div>\r\n");
      out.write("\t\t<p><strong>(Online Assignment submission System)</strong></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"templatemo_menu\">\r\n");
      out.write("    \t<div class=\"templatemo_menu_top\"></div>\r\n");
      out.write("        <ul>\r\n");
      out.write("          \t<li><a href=\"terms.jsp\">Terms</a></li>\r\n");
      out.write("            <li><a href=\"about\">About Us</a></li>\r\n");
      out.write("            <li><a href=\"mailto:punitporwal07@gmail.com>\">Help</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"templatemo_search\">\r\n");
      out.write("\t    <h2>Student Login</h2>\r\n");
      out.write(" <form name=\"thisform\" onSubmit=\"return validation()\" method=\"post\" action=\"verify.jsp\">        \t\t\t\t\t \r\n");
      out.write("          <div class=\"form_row\">\r\n");
      out.write("<label><strong>EnrollNo</strong></label><input name=\"EnrollNo\" type=\"text\" class=\"inputfield\" id=\"email_addremss\" maxlength=\"30\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form_row\">\r\n");
      out.write("<label><strong>Password</strong></label><input name=\"Password\" type=\"password\" class=\"inputfield\" id=\"password\" maxlength=\"30\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("         \r\n");
      out.write("          <input class=\"button\" type=\"submit\" name=\"Submit\" value=\"Login\" />\r\n");
      out.write("          <form action=\"home.html\">\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"templatemo_rightcolumn\">\r\n");
      out.write("\t<div id=\"templatemo_banner\">\r\n");
      out.write("\t  <h1>Welcome to Online Assignment Submission</h1>\r\n");
      out.write("      <p>Here any one can submit there hard work so called assignments from any where belonging to same organisation with a simple authentication required only...</p>\r\n");
      out.write("        <div class=\"readmore_darkblue\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t<div id=\"templatemo_two_column\">    \r\n");
      out.write("    \t<p>&nbsp;</p>\r\n");
      out.write("    \t<div class=\"two_columns_left\">\r\n");
      out.write("    \t  <h3>Our Services</h3>\r\n");
      out.write("            <p> Key aspects of OASS:</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("            \t<li>download forms</li>\r\n");
      out.write("                <li>Plagiarism                </li>\r\n");
      out.write("                <li>E-Commerce Store</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"readmore_black\"></div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("        \r\n");
      out.write("      <div class=\"two_columns_right\">\r\n");
      out.write("\t        <h3>Our Area</h3>\r\n");
      out.write("            <div class=\"news_area\">\r\n");
      out.write("              <p><strong>50+</strong></p>\r\n");
      out.write("              <p> LICENSED STUDENTS </p>\r\n");
      out.write("                <p>5+ </p>\r\n");
      out.write("                <p>FACULTIES</p>\r\n");
      out.write("                <p>belongs to SIRTS(IT)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"news_area\">\r\n");
      out.write("              <p>&nbsp;</p>\r\n");
      out.write("                <div class=\"readmore_black\"></div>\r\n");
      out.write("\t\t\t</div>            \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"templatemo_footer\">\r\n");
      out.write("<a href=\"#\">Home</a> | <a href=\"oass.jsp\">OASS</a> | <a href=\"about.jsp\">About</a> | <a href=\"terms.jsp\">Terms</a> | <a href=\"about.jsp\">Contact Us</a><br />\r\n");
      out.write("        Copyright &copy; 2010-2011 <a href=\"#\">OASS</a>- Designed by ADMINS<a href=\"http://www.templatemo.com\" target=\"_blank\"></a></div>       \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
